---
- name: Check and print current user
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get current user
      command: whoami
      register: whoami_output

    - name: Print current user
      debug:
        msg: "Current user is: {{ whoami_output.stdout }}"
