- name: check dir exist or not
  hosts: localhost
  gather_facts: yes
  tasks:

    - name: Get current date and time
      set_fact:
        current_date: "{{ ansible_date_time.iso8601 | regex_replace('T.*', '') }}"
        
    - name: Print current working directory
      command: pwd
      register: pwd_output
      
    - name: Create a test directory
      file:
        path: /home/ansiuser/Backup/test_dir
        state: directory
