---
- name: Monitor Memory and Disk Usage
  hosts: all
  become: yes
  vars:
    memory_threshold: 50  # Alert if memory usage exceeds 90%
    disk_threshold: 50    # Alert if disk usage exceeds 90%
    webhook_url: "https://discord.com/api/webhooks/1341011025926819861/iwbomQaEk5e6Y8MBRx47ln0hFPd-TPFBj3TjIwZBJfSSpfbSqAU0nM46Z023GgJamgQy"

  tasks:
    - name: Check Memory Usage
      shell: free | awk '/Mem/{printf("%.0f", $3/$2*100)}'
      register: memory_usage

    - name: Check Disk Usage
      shell: df -h / | awk 'NR==2 {print $5}' | sed 's/%//'
      register: disk_usage

    - name: Send Alert if Memory Exceeds Threshold
      uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        body: >
          {
            "text": "🚨 *Memory Alert!* Server: {{ inventory_hostname }} - Memory usage is at {{ memory_usage.stdout }}%"
          }
        headers:
          Content-Type: "application/json"
      when: memory_usage.stdout | int > memory_threshold

    - name: Send Alert if Disk Usage Exceeds Threshold
      uri:
        url: "{{ webhook_url }}"
        method: POST
        body_format: json
        body: >
          {
            "text": "🚨 *Disk Alert!* Server: {{ inventory_hostname }} - Disk usage is at {{ disk_usage.stdout }}%"
          }
        headers:
          Content-Type: "application/json"
      when: disk_usage.stdout | int > disk_threshold
